# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20160512_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebaseuser',
            name='userpoints',
        ),
    ]
