# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_knowledgebaseuser_userpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebaseuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='KnowledgeBaseUser',
        ),
    ]
