# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_useless_actived', models.BooleanField(default=False)),
                ('max_useless', models.IntegerField(null=True)),
                ('alert_view_actived', models.BooleanField(default=False)),
                ('min_view', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Manage Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('icon', models.CharField(default='Your Icon', help_text='Add an icon to your shortcut !', max_length=500)),
                ('activated', models.BooleanField(default=True)),
                ('static', models.BooleanField(default=False)),
                ('click_counter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Shortcut',
                'verbose_name_plural': 'Shortcuts',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='UserArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('article_id', models.IntegerField(default=0)),
                ('favorites', models.BooleanField(default=False)),
                ('visited', models.BooleanField(default=False)),
                ('searched', models.BooleanField(default=False)),
                ('readed', models.BooleanField(default=False)),
                ('useful', models.BooleanField(default=False)),
                ('date_visited', models.DateTimeField(default=datetime.datetime.now)),
                ('date_searched', models.DateTimeField(default=datetime.datetime.now)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'User Article',
                'verbose_name_plural': "User's Articles",
            },
        ),
        migrations.RemoveField(
            model_name='articletag',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articletag',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Tags that describe this article.', to='article.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 28, 8, 26, 16, 83601, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='', help_text="If omitted, the description will be determined by the first bit of the article's content."),
        ),
        migrations.AddField(
            model_name='article',
            name='expiration_date',
            field=models.DateTimeField(blank=True, help_text='Leave blank if the article does not expire.', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='favorite_counter',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 28, 8, 26, 20, 267730, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 28, 8, 26, 22, 363627, tzinfo=utc), help_text='The date and time this article shall appear online.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], default=('d', 'Draft'), max_length=1),
        ),
        migrations.AddField(
            model_name='article',
            name='useful_counter',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='article',
            name='view_counter',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AddField(
            model_name='shortcut',
            name='articles',
            field=models.ManyToManyField(blank=True, help_text='Tags that describe this article.', to='article.Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='feedback',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='article.Feedback'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags that describe this article.', to='article.Tag'),
        ),
    ]
