# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 13:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.RemoveField(
            model_name='articletag',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articletag',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='auto_tag',
            field=models.BooleanField(default=True, help_text='Check this if you want to automatically assign any existing tags to this article based on its content.'),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, help_text="If omitted, the description will be determined by the first bit of the article's content."),
        ),
        migrations.AddField(
            model_name='article',
            name='expiration_date',
            field=models.DateTimeField(blank=True, help_text='Leave blank if the article does not expire.', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='followup_for',
            field=models.ManyToManyField(blank=True, help_text='Select any other articles that this article follows up on.', related_name='followups', to='article.Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.TextField(blank=True, help_text='If omitted, the keywords will be the same as the article tags.'),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='The date and time this article shall appear online.'),
        ),
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='_article_related_articles_+', to='article.Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='sites',
            field=models.ManyToManyField(blank=True, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', unique_for_year='publish_date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags that describe this article.', to='article.Tag'),
        ),
    ]
