# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='icon',
            field=models.CharField(default='', help_text='Add an icon to your shortcut ! <a href="https://design.google.com/icons/">Click Here !</a>', max_length=500),
        ),
    ]
