# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160520_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Add an icon to your shortcut ! <a href="https://design.google.com/icons/">Click Here !</a>', max_length=500, null=True),
        ),
    ]
