# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160428_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='article.Comment')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_useless_actived', models.BooleanField(default=False)),
                ('max_useless', models.IntegerField(null=True)),
                ('alert_view_actived', models.BooleanField(default=False)),
                ('min_view', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Feedback Manager',
                'verbose_name_plural': 'Feedback Manager',
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelManagers(
            name='shortcut',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='alert_useless_actived',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='alert_view_actived',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='max_useless',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='min_view',
        ),
        migrations.AddField(
            model_name='feedback',
            name='explanation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rate',
            field=models.CharField(choices=[('0', 'Very Dissatisfied'), ('1', 'Dissatisfied'), ('2', 'Neutral'), ('3', 'Satisfied'), ('4', 'Very Satisfied')], default=('2', 'Neutral'), max_length=1),
        ),
        migrations.AddField(
            model_name='feedback',
            name='username',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='shortcut',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortcut',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortcut',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='article.Shortcut'),
        ),
        migrations.AddField(
            model_name='shortcut',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortcut',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='article',
            name='feedback',
        ),
        migrations.AddField(
            model_name='article',
            name='feedback',
            field=models.ManyToManyField(blank=True, help_text='Tags that describe this article.', to='article.Feedback'),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='icon',
            field=models.CharField(default='Your Icon', help_text='Add an icon to your shortcut ! <a href="https://design.google.com/icons/">Click Here !</a>', max_length=500),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='article',
            name='feedback_manager',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='article.FeedbackManager'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comments',
            field=models.ManyToManyField(blank=True, help_text='Tags that describe this article.', to='article.Comment'),
        ),
    ]
