# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20160520_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='article_id',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
