# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_feedback_article_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='article_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
        ),
    ]
