# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20160523_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='feedback',
            field=models.ManyToManyField(blank=True, help_text='Tags that describe this article.', to='article.Feedback'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='article_id',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
