# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20160523_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='feedback',
        ),
    ]
