# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_remove_article_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='article_id',
            new_name='article',
        ),
    ]
