# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20160523_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='daily_recap',
            field=models.BooleanField(default=False, help_text='This is a Daily Recap ?'),
        ),
        migrations.AddField(
            model_name='tag',
            name='click_counter',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
