# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('article', '0016_article_related_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authorized_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
