# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 06:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0019_remove_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authorized_user',
            field=models.ManyToManyField(blank=True, help_text='Choose one or several group you want to allow access to this specific article.', related_name='authorized_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_article', to=settings.AUTH_USER_MODEL),
        ),
    ]
