# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20160530_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='authorized_group',
            new_name='authorized_groups',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='authorized_user',
            new_name='authorized_users',
        ),
    ]
