# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_auto_20160530_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='author_article', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, help_text='Choose one or several group you want to allow access to this specific article.', related_name='authorized_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
