# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0024_auto_20160530_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author_a',
        ),
    ]
