# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0027_auto_20160530_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author_article',
            new_name='author',
        ),
    ]
