# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 01:03
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0028_auto_20160530_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file_content',
            field=models.FileField(default='/attachment/test.pdf', storage=django.core.files.storage.FileSystemStorage(location='/attachment/'), upload_to='article_files'),
        ),
    ]
