# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 01:12
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0030_auto_20160530_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file_content',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/static/core/'), upload_to='files'),
        ),
    ]
