# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 01:13
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0032_remove_article_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file_content',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/static/core/'), upload_to='files'),
        ),
    ]
