# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0034_auto_20160530_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='file_content_option',
            field=models.BooleanField(default=False, help_text='Check this box if you want to create your article from a PDF file. In this case you can let the title empty and it will be replaced by the file name (NOT RECOMMENDED).'),
        ),
        migrations.AlterField(
            model_name='article',
            name='file_content',
            field=models.FileField(blank=True, upload_to='article_pdf/%Y/%m/%d'),
        ),
    ]
