# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0035_auto_20160530_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url_content_option',
            field=models.BooleanField(default=False, help_text='Check this box if you want to create an article from a website. In this case when the user click onthe article he will be directly redirect to the url you entered.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='file_content_option',
            field=models.BooleanField(default=False, help_text='Check this box if you want to create an article from a PDF file. In this case you can let the title empty and it will be replaced by the file name (NOT RECOMMENDED).'),
        ),
    ]
