# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0038_auto_20160531_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='by_groups',
            field=models.BooleanField(default=True, help_text='And this one if you want to authorized specific groups.'),
        ),
        migrations.AddField(
            model_name='article',
            name='by_users',
            field=models.BooleanField(default=True, help_text='Check this box if you want to authorized specific users.'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Uncheck this box if you want to specified which groups or users are allowed to access this article.'),
        ),
    ]
