# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0039_auto_20160531_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='by_users',
            field=models.BooleanField(default=False, help_text='Check this box if you want to authorized specific users.'),
        ),
    ]
