# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0041_auto_20160531_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='by_groups_or_users',
            new_name='by_groups',
        ),
    ]
