# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 01:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0043_auto_20160531_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 1, 1, 13, 35, 517159, tzinfo=utc), help_text='The date and time this article shall appear online.'),
        ),
    ]
