# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 03:50
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('article', '0045_auto_20160531_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='daily_recap',
        ),
        migrations.RemoveField(
            model_name='dailyrecap',
            name='author',
        ),
        migrations.AddField(
            model_name='dailyrecap',
            name='authorized_groups',
            field=models.ManyToManyField(blank=True, help_text='Choose one or several group you want to allow access to this specific article.', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='dailyrecap',
            name='authorized_users_dr',
            field=models.ManyToManyField(blank=True, help_text='Choose one or several group you want to allow access to this specific article.', related_name='authorized_users_dr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyrecap',
            name='by_groups',
            field=models.BooleanField(default=True, help_text='And this one if you want to authorized specific groups.'),
        ),
        migrations.AddField(
            model_name='dailyrecap',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Uncheck this box if you want to specified which groups or users are allowed to access this article.'),
        ),
        migrations.AddField(
            model_name='dailyrecap',
            name='users',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 1, 3, 50, 31, 349796, tzinfo=utc), help_text='By default the article will be publish once you publish the article. But you can set your own date to publish this article later automatically.'),
        ),
    ]
