# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 05:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0047_auto_20160531_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyRecap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('daily_recap_id', models.IntegerField(default=0)),
                ('visited', models.BooleanField(default=False)),
                ('readed', models.BooleanField(default=False)),
                ('useful', models.BooleanField(default=False)),
                ('date_visited', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'User Daily Recap',
                'verbose_name_plural': "User's Daily Recaps",
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 1, 5, 10, 49, 70001, tzinfo=utc), help_text='By default the article will be publish once you publish the article. But you can set your own date to publish this article later automatically.'),
        ),
    ]
