# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 09:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0048_auto_20160601_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 2, 9, 41, 50, 314289, tzinfo=utc), help_text='By default the article will be publish once you publish the article. But you can set your own date to publish this article later automatically.'),
        ),
    ]
