# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 00:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0050_auto_20160606_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='static',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 8, 0, 43, 14, 273342, tzinfo=utc), help_text='By default the article will be publish once you publish the article. But you can set your own date to publish this article later automatically.'),
        ),
    ]
