# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 07:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0051_auto_20160607_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 8, 7, 23, 42, 310392, tzinfo=utc), help_text='By default the article will be publish once you publish the article. But you can set your own date to publish this article later automatically.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='name', max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
